import React from 'react'
import { ArrowUpRight, Check, MoveRight, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import { categories, products } from '../data/products'
import { ProductGrid } from '../components/ProductGrid'

export function Home() { return <main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">The autumn edit / 01</p><h1>Good things,<br /><em>well chosen.</em></h1><p className="hero-text">A thoughtful collection of objects for living, working, and getting away. Designed to be used, loved, and kept.</p><Link className="button button-dark" to="/products">Explore the collection <MoveRight size={16} /></Link></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1500&q=90" alt="Warmly styled living room with considered furniture" /><div className="hero-note">New arrivals<br /><strong>08.26</strong></div></div></section>
  <section className="section intro-section"><div><p className="eyebrow">Curated by nature</p><h2>Make room for<br /><em>the meaningful.</em></h2></div><p className="intro-text">NexaCart is a place for the pieces that quietly make a space feel like yours. Honest materials, useful forms, and a little bit of joy in the details.</p></section>
  <section className="section category-section"><div className="section-heading"><div><p className="eyebrow">Browse by mood</p><h2>Find your <em>next piece.</em></h2></div><Link className="text-link" to="/products">View all categories <ArrowUpRight size={15} /></Link></div><div className="category-grid">{categories.map((category) => <Link to={`/products?category=${category.name}`} className="category-card" key={category.name}><img src={category.image} alt="" /><div><span>{category.count}</span><h3>{category.name}</h3></div><ArrowUpRight size={19} /></Link>)}</div></section>
  <section className="section products-section"><div className="section-heading"><div><p className="eyebrow">The shortlist</p><h2>People are <em>loving.</em></h2></div><Link className="text-link" to="/products">Shop best sellers <ArrowUpRight size={15} /></Link></div><ProductGrid items={products.slice(0, 4)} /></section>
  <section className="feature-band"><div className="feature-image"><img src="https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=85" alt="Minimal workspace with a warm desk lamp" /></div><div className="feature-copy"><p className="eyebrow">The quiet edit</p><h2>Small changes.<br /><em>Big atmosphere.</em></h2><p>From the first coffee to the final page, find pieces that make everyday rituals feel a little more yours.</p><Link className="button button-light" to="/products?category=Workspace">Shop workspace <MoveRight size={16} /></Link><div className="feature-detail"><Check size={16} /> Thoughtfully sourced &nbsp;&nbsp; <Check size={16} /> Made to last</div></div></section>
  <section className="review-section"><div className="review-mark">“</div><blockquote>Beautifully edited. Every piece feels like something I’ll still want around in ten years.</blockquote><div className="review-byline"><span className="stars"><Star fill="currentColor" size={15} /><Star fill="currentColor" size={15} /><Star fill="currentColor" size={15} /><Star fill="currentColor" size={15} /><Star fill="currentColor" size={15} /></span> — Mara L., verified customer</div></section>
  <section className="newsletter"><p className="eyebrow">A note worth opening</p><h2>Good things, occasionally.</h2><p>New finds, considered stories, and 10% off your first order.</p><form><input type="email" placeholder="Your email address" aria-label="Email address" /><button className="button button-dark" type="submit">Sign me up <MoveRight size={16} /></button></form></section>
</main> }
