import React from 'react'
import { Heart, Minus, Plus, Star } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useDispatch, useSelector } from 'react-redux'
import { addToCart } from '../store/cartSlice'
import { toggleWishlist } from '../store/wishlistSlice'
import { products } from '../data/products'
import { ProductGrid } from '../components/ProductGrid'

export function ProductDetails() { const { id } = useParams(); const product = products.find((item) => item.id === Number(id)) || products[0]; const dispatch = useDispatch(); const wished = useSelector((state) => state.wishlist.items.some((item) => item.id === product.id)); return <main className="detail-page"><div className="breadcrumbs"><Link to="/products">Collection</Link> / {product.category} / {product.name}</div><section className="detail-layout"><div className="detail-gallery"><img src={product.image} alt={product.name} /><div className="gallery-thumb"><img src={product.image} alt="" /></div></div><div className="detail-copy"><p className="eyebrow">{product.brand}</p><h1>{product.name}</h1><div className="detail-rating"><Star size={15} fill="currentColor" /> {product.rating} <span>({product.reviews} reviews)</span></div><div className="detail-price"><strong>${product.price}</strong><del>${product.originalPrice}</del><span>{Math.round((1 - product.price / product.originalPrice) * 100)}% off</span></div><p className="detail-description">A quietly distinctive essential, designed around the details that matter. Thoughtful proportions, tactile materials, and a finish that gets better with time.</p><div className="option"><label>Colour <b>{product.color}</b></label><button className="color-swatch" aria-label={product.color}></button></div><div className="purchase-row"><div className="quantity"><button aria-label="Decrease quantity"><Minus size={15} /></button><span>1</span><button aria-label="Increase quantity"><Plus size={15} /></button></div><button className="button button-dark add-detail" onClick={() => dispatch(addToCart(product))}>Add to bag</button><button className={wished ? 'detail-wish wished' : 'detail-wish'} onClick={() => dispatch(toggleWishlist(product))} aria-label="Toggle wishlist"><Heart size={19} fill={wished ? 'currentColor' : 'none'} /></button></div><div className="detail-perks"><p>Free delivery on orders over $150</p><p>30-day easy returns</p><p>Crafted with considered materials</p></div></div></section><section className="detail-related"><div className="section-heading"><h2>You may also <em>like.</em></h2><Link className="text-link" to="/products">See the collection</Link></div><ProductGrid items={products.filter((item) => item.id !== product.id).slice(0, 4)} /></section></main> }
